# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grammar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrammar.proto\x12\x07grammar\"\x1e\n\x0eGrammarRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\")\n\x0fGrammarResponse\x12\x16\n\x0e\x63orrected_text\x18\x01 \x01(\t2U\n\x0eGrammarService\x12\x43\n\x0e\x43orrectGrammar\x12\x17.grammar.GrammarRequest\x1a\x18.grammar.GrammarResponseB\x11Z\x0fyour/go/packageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grammar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017your/go/package'
  _GRAMMARREQUEST._serialized_start=26
  _GRAMMARREQUEST._serialized_end=56
  _GRAMMARRESPONSE._serialized_start=58
  _GRAMMARRESPONSE._serialized_end=99
  _GRAMMARSERVICE._serialized_start=101
  _GRAMMARSERVICE._serialized_end=186
# @@protoc_insertion_point(module_scope)
