# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grammar_pb2 as grammar__pb2


class GrammarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CorrectGrammar = channel.unary_unary(
                '/grammar.GrammarService/CorrectGrammar',
                request_serializer=grammar__pb2.GrammarRequest.SerializeToString,
                response_deserializer=grammar__pb2.GrammarResponse.FromString,
                )


class GrammarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CorrectGrammar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrammarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CorrectGrammar': grpc.unary_unary_rpc_method_handler(
                    servicer.CorrectGrammar,
                    request_deserializer=grammar__pb2.GrammarRequest.FromString,
                    response_serializer=grammar__pb2.GrammarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grammar.GrammarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrammarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CorrectGrammar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grammar.GrammarService/CorrectGrammar',
            grammar__pb2.GrammarRequest.SerializeToString,
            grammar__pb2.GrammarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
